apiVersion: v2
name: helm-parent
description: Jokes System Parent Helm chart for Kubernetes
type: application
version: 1.0.0-SNAPSHOT
appVersion: "1.0.0-SNAPSHOT"
dependencies:
  - name: jokes-service
    version: 1.0.0-SNAPSHOT
    repository: file://../jokes-service/helm/jokes-service
    condition: jokes-service.enabled
  - name: jokes-ui
    version: 1.0.0-SNAPSHOT
    repository: file://../jokes-ui/helm/jokes-ui
    condition: jokes-ui.enabled
  - name: postgresql
    version: 11.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
