jokes-service:
  enabled: true
  service:
    type: LoadBalancer
    port: 4001
jokes-ui:
  enabled: true
  service:
    type: LoadBalancer
    port: 4000
postgresql:
  enabled: true
  auth:
    postgresPassword: password
    database: jokes
  primary:
    initdb:
      user: postgres
      password: password
      scripts:
        dbinit.sql: |
          CREATE USER jokes WITH ENCRYPTED PASSWORD 'password';
          GRANT ALL PRIVILEGES ON DATABASE jokes TO jokes;
